image: bars21/dev_hep_root:6.24.00gcc9

stages:
  - build

compile:
  stage: build
  before_script:
    - . $COMMON_INSTALL_PREFIX/setup.sh
    - git submodule update --init --recursive
    - mkdir build; cd build
    - gcc -v > ../gcc.log
  script:
    - cmake3 ../
    - make 2>&1 | tee -a ../gcc.log
  artifacts:
    paths:
      - ./build/app/Converter.exe
      - ./build/app/Monitor.exe
      - gcc.log
